### DISCUSSION TITLE
Zwei Sensoren an einem ESP?

### DISCUSSION THREAD

**Discussion by nraeth** [jensrossbach/esphome-ferraris-meter#8] [Q&A]
Hallo zusammen,

ich habe zwei Stromzähler nebeneinander. Ich vermute, dass ich auch zwei Sensoren an nur einem ESP betreiben kann?

Wie müsste ich dafür denn vorgehen?

Gruß 
Niels

**Comment by jensrossbach** [comment]
Hi Niels,

der ESP kann natürlich auch zwei Stromzähler überwachen, vorausgesetzt es ist noch ein weiterer GPIO-Pin für das zweite TCRT5000-Modul übrig (was höchstwahrscheinlich der Fall sein wird, wenn der ESP nicht noch für zig andere Zwecke verwendet wird). Allerdings ist die Ferraris-Komponente momentan nicht Multi-Instanz-fähig. Um das zu unterstützen, sollte aber nur eine kleine Änderung im Code nötig sein. Könntest du dazu einen Feature-Request erstellen? Dann würde ich die nötige Änderung machen.

Sobald das dann unterstützt wird, sollte es mit folgender Konfiguration möglich sein, zwei Stromzähler zu unterstützen (das folgende Beispiel ist aber nur ein Auszug und nicht vollständig):

```yaml
ferraris:
  - id: ferraris_meter_1
    pin: GPIO4
    rotations_per_kwh: 75
    low_state_threshold: 400
  - id: ferraris_meter_2
    pin: GPIO5
    rotations_per_kwh: 75
    low_state_threshold: 400

sensor:
  - platform: ferraris
    ferraris_id: ferraris_meter_1
    power_consumption:
      name: Momentanverbrauch 1
    energy_meter:
      name: Verbrauchszähler 1
  - platform: ferraris
    ferraris_id: ferraris_meter_2
    power_consumption:
      name: Momentanverbrauch 2
    energy_meter:
      name: Verbrauchszähler 2

binary_sensor:
  - platform: ferraris
    ferraris_id: ferraris_meter_1
    rotation_indicator:
      name: Umdrehungsindikator 1
  - platform: ferraris
    ferraris_id: ferraris_meter_2
    rotation_indicator:
      name: Umdrehungsindikator 2

switch:
  - platform: ferraris
    ferraris_id: ferraris_meter_1
    calibration_mode:
      name: Kalibrierungsmodus 1
  - platform: ferraris
    ferraris_id: ferraris_meter_2
    calibration_mode:
      name: Kalibrierungsmodus 2
```
