### ISSUE TITLE
Support analog input with threshold as alternative to digital input

### ISSUE THREAD

**Issue by jensrossbach** [jensrossbach/esphome-ferraris-meter#21]
Add support for an analog sensor as input for rotation detection together with a threshold as discussed in https://github.com/jensrossbach/esphome-ferraris-meter/discussions/18.

<div type='discussions-op-text'>

<sup>Originally posted by **digitalbirdo** October 30, 2024</sup>
#### Use ADC with threshold instead of digital input
I had a lot of trouble correctly adjusting the potentiometer on the TCRT5000. Even a modification to a Schmitt-Trigger did not help to get consistant results.

I did a quick hack to read the analog output of the TCRT5000 and switch an output pin to on/off.
I connected GPIO4 diretcly to GPIO5.

It would be a bit nicer to have the possibility of an ADC as an input with an configurable threshold instead of fiddling around with the potentiometer :)

```yaml
sensor:
  - platform: adc
    pin: GPIO17
    id: ferraris_adc
    name: "Ferraris_Raw"
    internal: true
    raw: true
    samples: 10
    update_interval: 50ms
    on_value:
     then:
       lambda: |-
         if (id(ferraris_adc).state < id(ferraris_adc_threshold).state) {
             id(gpio_d1).turn_on();
         }
         else {
             id(gpio_d1).turn_off();
         }

number:
  - platform: template
    id: ferraris_adc_threshold
    name: ADC Schwellwert
    icon: mdi:counter
    entity_category: config
    mode: box
    optimistic: true
    restore_value: true
    initial_value: 58
    min_value: 0
    max_value: 1000
    step: 1

switch:
  - platform: gpio
    # connected to GPIO4 which serves as input for the ferraris component
    pin: GPIO5
    id: gpio_d1
```
</div>

**Comment by jensrossbach** [comment]
@digitalbirdo, I pushed a first implementation of your idea on branch `feature_request/21`. Could you please test this code and give feedback if it is working well?

You can change the `external_components` entry in your YAML file to use the new code:
```yaml
external_components:
  - source: github://jensrossbach/esphome-ferraris-meter@feature_request/21
    components: [ferraris]
```

The configuration which is necessary to support the new analog input can be found in the adapted [documentation](https://github.com/jensrossbach/esphome-ferraris-meter/blob/feature_request/21/README.md) or in the provided [example configuration](https://github.com/jensrossbach/esphome-ferraris-meter/blob/feature_request/21/example_config/ferraris_meter_analog.yaml).
