### ISSUE TITLE
Configured restore mode of calibration mode switch is not respected

### ISSUE THREAD

**Issue by jensrossbach** [jensrossbach/esphome-ferraris-meter#40]
**Describe the bug**
Configured restore modes for the calibration mode switch have no effect. The calibration mode switch is always `off` at startup.

**To reproduce**
1. Configure a restore mode other than always `off`.
2. Restart microcontroller.
3. Check state of calibration mode switch.

**Expected behavior**
The configured restore mode for the calibration mode switch is respected.

**Logs and configuration**
```yaml
switch:
  - platform: ferraris
    calibration_mode:
      name: Calibration mode
      restore_mode: ALWAYS_ON
```

**Context information**
Please complete the following information.
 - ESPHome version: n/a
 - Ferraris Meter version: 1.4.0
 - Microcontroller type (e.g., ESP32, ESP8266): n/a

**Additional information**
None
