### ISSUE TITLE
Automation for copy Value

### ISSUE THREAD

**Issue by metaiiica** [jensrossbach/esphome-ferraris-meter#64]
### Current behavior

![Image](https://github.com/user-attachments/assets/3ac9d50c-c047-45ee-89c1-a93fbbcd041f)

### Expected behavior

geht the error picture above.

Helper added

this is my automation:

alias: Aktualisierung Verbrauchszähler-Cache
description: ""
triggers:
  - entity_id:
      - sensor.verbrauchszahler
    trigger: state
conditions: []
actions:
  - action: input_number.set_value
    target:
      entity_id: input_number.stromzaehler_letzter_wert
    data:
      value: "{{ states(trigger.entity_id) }}"
mode: single

![Image](https://github.com/user-attachments/assets/4a5b8ab6-7098-42cd-84a8-1aec73a771eb)

### Steps to reproduce

when i test action

### Configuration

```yaml
esphome:
  name: stromzahler

esp8266:
  board: d1_mini
  
# include Ferraris component (mandatory)
external_components:
  - source: github://jensrossbach/esphome-ferraris-meter@v1.5.1
    components: [ferraris]


# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxx"

wifi:
  ssid: "xxxxx"
  password: "xxxxx"
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stromzahler Fallback Hotspot"
    password: "xxxx"

captive_portal:
web_server:
  port: 80


# Ferraris component (mandatory)
ferraris:
  id: ferraris_meter
  digital_input: GPIO14
  energy_start_value: last_energy_value

# numeric sensors
sensor:
  - platform: ferraris
    # sensor for current power consumption
    power_consumption:
      name: Momentanverbrauch
    # sensor for energy meter reading
    energy_meter:
      name: Verbrauchszähler
  # sensor for Wi-Fi signal strength
  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 60s

# binary sensors
binary_sensor:
  - platform: ferraris
    # sensor for indicating detected rotation during calibration mode
    rotation_indicator:
      name: Umdrehungsindikator
  # sensor for wireless connection status
  - platform: status
    name: Status

# number components
number:
  # import entity holding last energy meter reading from Home Assistant
  - platform: homeassistant
    id: last_energy_value
    entity_id: input_number.stromzaehler_letzter_wert
  # number used to manually overwrite the energy meter
  - platform: template
    id: target_energy_value
    name: Manueller Zählerstand
    icon: mdi:counter
    unit_of_measurement: kWh
    device_class: energy
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1000000
    step: 0.01

# switch components
switch:
  - platform: ferraris
    # switch used to activate or deactivate the calibration mode
    calibration_mode:
      name: Kalibrierungsmodus

# button components
button:
  # button used to trigger the manual overwriting of the energy meter
  - platform: template
    name: Verbrauchszähler überschreiben
    icon: mdi:download
    entity_category: config
    on_press:
      - ferraris.set_energy_meter:
          id: ferraris_meter
          value: !lambda |-
            float val = id(target_energy_value).state;
            return (val >= 0) ? val : 0;
```

### ESPHome version

2025.6.2

### Ferraris version

1.5.1

### Microcontroller type

esp8266
